//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAdmin
    {
        public int MaAdmin { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string TenAdmin { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<bool> VaiTro { get; set; }
    }
}
