//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAlbum()
        {
            this.tbYeuThiches = new HashSet<tbYeuThich>();
        }
    
        public int MaAlbum { get; set; }
        public string TenAlbum { get; set; }
        public string AnhAlbum { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> MaND { get; set; }
    
        public virtual tbNguoiDung tbNguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbYeuThich> tbYeuThiches { get; set; }
    }
}
