//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBinhLuan
    {
        public int MaBinhLuan { get; set; }
        public string NoiDungBinhLuan { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> MaNhac { get; set; }
        public Nullable<int> MaND { get; set; }
    
        public virtual tbNguoiDung tbNguoiDung { get; set; }
        public virtual tbNhac tbNhac { get; set; }
    }
}
