//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMV
    {
        public int MaMV { get; set; }
        public string TenMV { get; set; }
        public string LinkNhung { get; set; }
        public Nullable<int> MaTheLoai { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public string LoiBaiHat { get; set; }
    }
}
