//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTheLoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTheLoai()
        {
            this.tbNhacs = new HashSet<tbNhac>();
        }
    
        public int MaTheLoai { get; set; }
        public string TenTheLoai { get; set; }
        public string AnhTheloai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbNhac> tbNhacs { get; set; }
    }
}
