//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTrinhBay
    {
        public int MaTrinhBay { get; set; }
        public Nullable<int> MaNhac { get; set; }
        public Nullable<int> MaCaSi { get; set; }
    
        public virtual tbCaSi tbCaSi { get; set; }
        public virtual tbNhac tbNhac { get; set; }
    }
}
