//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTraLoi
    {
        public int MaTraLoi { get; set; }
        public string NoiDungTraLoi { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> MaBinhLuan { get; set; }
        public Nullable<int> MaND { get; set; }
    
        public virtual tbBinhLuan tbBinhLuan { get; set; }
        public virtual tbNguoiDung tbNguoiDung { get; set; }
    }
}
